apiVersion: batch/v1
kind: Job
metadata:
  name: certificate-patch-job
  namespace: cluster-gitops
  generateName: certificate-patch-job-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-type: Job
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: patcher
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Patching Proxy..."
              oc patch proxy cluster --type='json' \
                -p='[{"op": "add", "path": "/spec/trustedCA", "value": {"name": "trusted-ca"}}]'
              
              echo "Patching IngressController..."
              oc patch ingresscontroller.operator default \
                --type=merge \
                -n openshift-ingress-operator \
                -p '{"spec":{"defaultCertificate": {"name": "apps-ocp-lab-snimmo-com-tls"}}}'
              
              echo "Patching APIServer..."
              oc patch apiserver cluster \
                --type=merge \
                -p '{"spec":{"servingCerts": {"namedCertificates": [{"names": ["api.ocp.lab.snimmo.com"], "servingCertificate": {"name": "api-ocp-lab-snimmo-com-tls"}}]}}}'
      restartPolicy: Never
      serviceAccount: certificate-patch
      serviceAccountName: certificate-patch
  backoffLimit: 4
