apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-patcher-sa
  namespace: openshift-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificate-patcher-cluster-role
rules:
  - apiGroups: ["config.openshift.io"]
    resources: ["proxies", "apiservers"]
    verbs: ["get", "patch"]
  - apiGroups: ["operator.openshift.io"]
    resources: ["ingresscontrollers"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certificate-patcher-sa-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certificate-patcher-cluster-role
subjects:
  - kind: ServiceAccount
    name: certificate-patcher-sa
    namespace: openshift-config
---
apiVersion: batch/v1
kind: Job
metadata:
  name: certificate-patch-job
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: certificate-patcher-sa
      restartPolicy: Never
      containers:
        - name: patcher
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Patching Proxy..."
              oc patch proxy cluster --type='json' \
                -p='[{"op": "add", "path": "/spec/trustedCA", "value": {"name": "trusted-ca"}}]'
              
              echo "Patching IngressController..."
              oc patch ingresscontroller.operator default \
                --type=merge \
                -n openshift-ingress-operator \
                -p '{"spec":{"defaultCertificate": {"name": "apps-ocp-lab-snimmo-com-tls"}}}'
              
              echo "Patching APIServer..."
              oc patch apiserver cluster \
                --type=merge \
                -p '{"spec":{"servingCerts": {"namedCertificates": [{"names": ["api.ocp.lab.snimmo.com"], "servingCertificate": {"name": "api-ocp-lab-snimmo-com-tls"}}]}}}'
  backoffLimit: 2
