apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-ocp-lab-snimmo-com-certificate
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  commonName: apps.ocp.lab.snimmo.com
  dnsNames:
    - "apps.ocp.lab.snimmo.com" 
    - "*.apps.ocp.lab.snimmo.com"
  secretName: apps-ocp-lab-snimmo-com-tls
  isCA: false
  issuerRef:
    group: cert-manager.io
    name: lets-encrypt-cluster-issuer
    kind: ClusterIssuer