apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-cluster-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      name: acme-account-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token-secret