apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundation
  namespace: cluster-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cluster
  source:
    repoURL: https://github.com/snimmo/openshift-cluster-gitops.git
    targetRevision: main
    path: foundation
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true