apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-cnv
  namespace: cluster-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: cluster
  source:
    repoURL: https://github.com/snimmo/openshift-cluster-gitops.git
    targetRevision: main
    path: openshift-cnv
  destination:
    server: https://kubernetes.default.svc
    namespace: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true