apiVersion: kustomize.config.k8s.io/v1beta1   
kind: Kustomization
metadata:
  name: foundation

resources:
  - certificate-patch-rbac.yaml
  - enable-console-plugin-rbac.yaml
  - label-node-rbac.yaml