apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: cluster-gitops
  labels:
    app.kubernetes.io/name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: cluster
  source:
    repoURL: https://github.com/snimmo/openshift-cluster-gitops.git
    targetRevision: main
    path: external-secrets
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true