apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: {}