apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: test-external-secret
  data:
    - secretKey: username
      remoteRef:
        key: secrets/test/testvalues
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/test/testvalues
        property: password
