apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-label-manager
  namespace: openshift-gitops-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-label-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-label-manager-role-binding
subjects:
  - kind: ServiceAccount
    name: node-label-manager
    namespace: openshift-gitops-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-label-manager-role