apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: https://vault.lab.snimmo.com:8200
      path: secrets
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: openshift-config
