kind: Deployment
apiVersion: apps/v1
metadata:     
  name: my-app-1
  namespace: my-app-1
  labels:
    app: my-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-1   
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
      - name: my-app-1
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: LOG_LEVEL
          value: "debug"
        - name: FEATURE_FLAG
          value: "true"
        - name: API_ENDPOINT
          value: "https://api.dev.example.com"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"   
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:    
