apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-ocp-lab-snimmo-com-certificate
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  commonName: api.ocp.lab.snimmo.com
  dnsNames:
    - "api.ocp.lab.snimmo.com" 
  secretName: api-ocp-lab-snimmo-com-tls
  isCA: false
  issuerRef:
    group: cert-manager.io
    name: lets-encrypt-cluster-issuer
    kind: ClusterIssuer