apiVersion: batch/v1
kind: Job
metadata:
  name: label-storage-nodes
  generateName: label-storage-nodes-
  namespace: openshift-gitops-cluster
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-type: Job
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: label-storage-nodes
          image: registry.redhat.io/openshift4/ose-cli:latest
          env:
            - name: selector
              value: 'node-role.kubernetes.io/worker'
          command:
            - /bin/bash
            - -c
            - |
              nodes=$(oc get nodes --selector=${selector} -o name)
              node_count=$(echo "${nodes}" | wc -l)
              if [ "${node_count}" -lt 3 ]; then
                echo "Not enough selected nodes present in cluster"
                echo "${nodes}"
                exit 1
              fi

              echo "Checking and labeling eligible nodes..."
              for node in ${nodes}; do
                name=$(echo "$node" | cut -d/ -f2)
                label=$(oc get "$node" -o jsonpath='{.metadata.labels.cluster\.ocs\.openshift\.io/openshift-storage}')
                if [ -z "$label" ]; then
                  echo "Labeling node: $name"
                  oc label node "$name" cluster.ocs.openshift.io/openshift-storage=""
                else
                  echo "Node $name already labeled. Skipping."
                fi
              done
      restartPolicy: Never
      serviceAccount: node-label-manager
      serviceAccountName: node-label-manager
  backoffLimit: 3
