apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan4-net-noipam
  namespace: default
spec:
  config: '{ 
      "cniVersion": "0.3.1", 
      "type": "bridge", 
      "bridge": "br-vlan4"
    }'