apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan4-bridge-on-bond0
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
      - name: vlan4
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 4
      - name: br-vlan4
        type: linux-bridge
        state: up
        bridge:
          port:
            - name: vlan4
