apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-kube-descheduler
resources:
  - cluster-kube-descheduler.yaml
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml